modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="sa"
version="2.0.0"
displayName="Simply Additions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="TheOnlyGalaxyGaming, MCreator"

[[dependencies.sa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




